### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by mlaval** [angular/ts2dart#157]
This is what I get when running the tasks on a Windows machine.

gulp compile
```
[18:30:56] Starting 'compile'...
lib\main.ts(1,1): 6053 File 'd:/Github/ts2dart_mlaval/typings/fs-extra/fs-extra.d.ts' not found.
[18:30:58] lib\main.ts(1,1): 6053 File 'd:/Github/ts2dart_mlaval/typings/fs-extra/fs-extra.d.ts' not found.
```

gulp test
```
[18:31:02] Starting 'compile'...
[18:31:02] Starting 'test.check-format'...
[18:31:02] 'test.check-format' errored after 160 ms
[18:31:02] Error: 3221225781
    at formatError (c:\Users\mlaval\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (c:\Users\mlaval\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (d:\Github\ts2dart_mlaval\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at d:\Github\ts2dart_mlaval\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (d:\Github\ts2dart_mlaval\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at DestroyableTransform.<anonymous> (d:\Github\ts2dart_mlaval\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:52:4)
    at DestroyableTransform.f (d:\Github\ts2dart_mlaval\node_modules\gulp\node_modules\orchestrator\node_modules\end-of-stream\node_modules\once\once.js:17:25)
    at DestroyableTransform.emit (events.js:129:20)
    at onwriteError (d:\Github\ts2dart_mlaval\node_modules\gulp-clang-format\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:250:10)
lib\main.ts(1,1): 6053 File 'd:/Github/ts2dart_mlaval/typings/fs-extra/fs-extra.d.ts' not found.
[18:31:04] lib\main.ts(1,1): 6053 File 'd:/Github/ts2dart_mlaval/typings/fs-extra/fs-extra.d.ts' not
 found.
```

As a consequence, it seems that all Dart tasks of angular/angular are also failing (`build.dart`, `test.unit.dart`, ...).

**Comment by mprobst** [comment]
Have you run `tsd install` after checking out the code? Does the `.d.ts` file mentioned actually exist?

**Comment by mlaval** [comment]
Tried again with the latest code base and a clean `npm install`:
 - `gulp compile` works fine
 - `gulp test` works fine with the fix proposed in #164

**Comment by mprobst** [comment]
I assume this is fixed?

**Comment by mlaval** [comment]
The tasks are now fully working.
I'm now getting 7 failing unit tests, but I'll look at this later.

For the record:
```
  1) main transpiler functionality errors reports relative paths in errors:
     AssertionError: expected [Function] to throw error matching /^b\/c.ts:1/ but got 'b\\c.ts:1:1:
delete operator is unsupported'
      at Context.<anonymous> (/source/test/main_test.ts:33:71)

  2) main transpiler functionality output paths writes within the path:

      AssertionError: expected '\\x\\b\\c.dart' to equal '/x/b/c.dart'
      + expected - actual

      -\x\b\c.dart
      +/x/b/c.dart

      at Context.<anonymous> (/source/test/main_test.ts:40:67)

  3) main transpiler functionality output paths defaults to writing to the same location:

      AssertionError: expected '\\a\\b\\c.dart' to equal '/a/b/c.dart'
      + expected - actual

      -\a\b\c.dart
      +/a/b/c.dart

      at Context.<anonymous> (/source/test/main_test.ts:48:67)

  4) main transpiler functionality source maps maps locations:
     Error: "path/test.ts" is not in the SourceMap.
      at Context.<anonymous> (/source/test/main_test.ts:80:28)

  5) library name adds a library name:

      AssertionError: expected ' library b_c ; var x ;' to equal ' library b.c ; var x ;'
      + expected - actual

      - library b_c ; var x ;
      + library b.c ; var x ;

      at Context.<anonymous> (/source/test/module_test.ts:62:25)

  6) library name handles reserved words:

      AssertionError: expected 'for_in_do_x' to equal '_for._in._do.x'
      + expected - actual

      -for_in_do_x
      +_for._in._do.x

      at Context.<anonymous> (/source/test/module_test.ts:67:65)

  7) library name handles built-in and limited keywords:

      AssertionError: expected 'as_if_sync_x' to equal 'as._if.sync.x'
      + expected - actual

      -as_if_sync_x
      +as._if.sync.x

      at Context.<anonymous> (/source/test/module_test.ts:70:66)
```

**Comment by mprobst** [comment]
I wonder if we can get TypeScript to not use backslashes? I'm somewhat hesitant to put `path.separator` all over our unit tests, that won't help readability much.
