### ISSUE TITLE
Unexpected token error with simplest typescript code

### ISSUE THREAD

**Issue by aleksfes** [angular/ts2dart#371]
Hi, guys!

I am trying to use Angular2 typescript plugins with my Angular2/Dart web app, but I've got some errors even with hello world simplest example.

For example such code
```typescript
class Greeter {
    constructor(public greeting: string) { }
    greet() {
        return "<h1>" + this.greeting + "</h1>";
    }
};

var greeter = new Greeter("Hello, world!");
```
produces error
```text
[12:08:59] Error: ts2dart-test/hello-world-simple.ts:1:1: Could not format because the source could not be parsed:

line 1, column 2: Unexpected token 'class'
 class Greeter { String greeting ; Greeter ( this . greeting ) { } greet ( ) { return "<h1>" + this . greeting + "</h1>" ; } } ; var greeter = new Greeter ( "Hello, world!" ) ;
 ^^^^^
    at Transpiler.reportError (/source/main.ts:280:38)
    at Transpiler.formatCode (/source/main.ts:214:12)
    at Transpiler.translate (/source/main.ts:208:17)
    at /source/main.ts:137:31
    at Array.forEach (native)
    at Transpiler.transpile (/source/main.ts:136:10)
    at Gulp.<anonymous> (/.../gulpfile.js:15:16)
    at module.exports (/.../node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/.../node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/.../node_modules/orchestrator/index.js:214:10)
```

I'm using node@4.4.7, npm@3.10.5, ts2dart@0.9.10 and gulp to run transpilation:
```javascript
const ts2dart = require('ts2dart');

gulp.task('ttt', () => {
    const transpiler = new ts2dart.Transpiler({
        generateLibraryName: false,
        failFast: true
    });
    transpiler.transpile([
        'ts2dart-test/hello-world-simple.ts'
    ], './temp');
});
```

Could you please help me to figure out what is wrong?

**Comment by mprobst** [comment]
Sorry that the error is this obscure (dartfmt is not very resilient). The problem is that the `var greeter = new Greeter("Hello, world!");` part of your code cannot be translated to valid Dart. You cannot initialize variables in the global scope like that, they must be in some function body.

Let me know if that helps, and please reopen if it doesn't!

**Comment by aleksfes** [comment]
Hi, mprobst!

Thanks for your answer. I've tried your suggestion, but still have the error.

ts file:
```javascript
class Greeter {
    constructor(public greeting: string) { }
    greet() {
        return "<h1>" + this.greeting + "</h1>";
    }
};

function test() {
    var greeter = new Greeter("Hello, world!");
}
```

error:
```text
$ gulp compile-ts
[13:29:54] Using gulpfile ~/dev/test-gulp-ts2dart/gulpfile.js
[13:29:54] Starting 'compile-ts'...
[13:29:54] Finished 'compile-ts' after 10 ms
[13:29:54] test.ts:1:1: Could not format because the source could not be parsed:

line 1, column 17: Unexpected token 'class'
 library test ; class Greeter { String greeting ; Greeter ( this . greeting ) { } greet ( ) { return "<h1>" + this . greeting + "</h1>" ; } } ; test ( ) { var greeter = new Greeter ( "Hello, world!" ) ; }
                ^^^^^
[13:29:54] ts2dart transpilation failed.

.../dev/test-gulp-ts2dart/node_modules/gulp-ts2dart/index.js:48
          throw new Error('ts2dart transpilation failed.');
                ^
Error: ts2dart transpilation failed.
    at DestroyableTransform.finished [as _flush] (.../dev/test-gulp-ts2dart/node_modules/gulp-ts2dart/index.js:48:17)
    at DestroyableTransform.<anonymous> (.../dev/test-gulp-ts2dart/node_modules/gulp-ts2dart/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
    at finishMaybe (.../dev/test-gulp-ts2dart/node_modules/gulp-ts2dart/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (.../dev/test-gulp-ts2dart/node_modules/gulp-ts2dart/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at DestroyableTransform.Writable.end (.../dev/test-gulp-ts2dart/node_modules/gulp-ts2dart/node_modules/readable-stream/lib/_stream_writable.js:356:5)
    at DestroyableTransform.onend (.../dev/test-gulp-ts2dart/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:260:16)
```

What should I try now?

**Comment by mprobst** [comment]
The problem is the trailing semicolon after the class statement, Dart doesn't allow empty statements in the body of a Dart file. You can debug this more easily by taking the code from the error message and pasting it into e.g. dartpad – apparently most other Dart parsers have better error reporting.

On a more general note, `ts2dart` was built as a specialized tool to translate the Angular 2 code base. It's not designed to work on arbitrary TypeScript code bases, and I suspect you'll run into lots of issues trying to use it. I wouldn't recommend it as a way to consume arbitrary TypeScript libraries from Dart. On the other hand, I don't know of any other way.

**Comment by aleksfes** [comment]
> The problem is the trailing semicolon after the class statement, Dart doesn't allow empty statements in the body of a Dart file. You can debug this more easily by taking the code from the error message and pasting it into e.g. dartpad – apparently most other Dart parsers have better error reporting.

It works now after removing the semicolon!
Also dartpad reports the error correctly. Thanks!


> On a more general note, ts2dart was built as a specialized tool to translate the Angular 2 code base. It's not designed to work on arbitrary TypeScript code bases, and I suspect you'll run into lots of issues trying to use it. I wouldn't recommend it as a way to consume arbitrary TypeScript libraries from Dart. On the other hand, I don't know of any other way.

Yes, it was my goal to make some TypeScript plugins (ng2-select, ng2-modal, angular2-hot-loader) to work with Angular2-Dart application. Instead I will try to use ports of these plugins.

@mprobst , thanks a lot!
